# Dependencies
markdown: redcarpet
highlighter: true

# Permalinks
permalink: pretty

# Setup
title: Artificial Dev
description: 'Blog about Artifical Intelligence, Data Science and Python.'


url: https://www.artificialdev.com   # with the https protocol
enforce_ssl: www.artificialdev.com   # without any protocol

# For example, my configuration is this:
url: https://artificialdev.com
enforce_ssl: artificialdev.com

author:
  name: 'Sean Anthony Quinn'

twitter_username: SQuinn7
github_username: seanquinn
linkedin_username: squinn423
email: squinn423@gmail.com

paginate: 5

excerpt_separator: "<!--excerpt-->"

gems: [redcarpet, pygments.rb, jekyll-paginate]
